services:
  - type: web
    name: freight-flow-socket
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: EMIT_SECRET
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false